export default datum = [
  {
    id: 0,
    address: "5612 Harmony Ave",
    amount: 1000,
    payment: true,
    date: "03/03/21",
    transactionType: "Rent Payment",
    paymentType: "Auto Payment Collection",
    notes: null,
    image: {},
  },
  {
    id: 1,
    address: "123 Main Street",
    amount: 1000,
    payment: true,
    date: "03/01/21",
    transactionType: "Rent Payment",
    paymentType: "Auto Payment Collection",
    notes: null,
    image: {},
  },
  {
    id: 2,
    address: "1012 Horizon Ridge",
    amount: 250,
    payment: false,
    date: "02/28/21",
    transactionType: "Repairs",
    paymentType: "Check",
    notes: null,
    image: {},
  },
  {
    id: 3,
    address: "595 S. Green Valley Pkwy Apt 121",
    amount: 2500,
    payment: true,
    date: "02/28/21",
    transactionType: "Rent Payment",
    paymentType: "Auto Payment Collection",
    notes: null,
    image: {},
  },
  {
    id: 4,
    address: "101 Univeristy Dr. Unit 100",
    amount: 500,
    payment: false,
    date: "02/28/21",
    transactionType: "Repairs",
    paymentType: "Credit Card",
    notes: "Hello World",
    image: {},
  },
];
